fix predeploy

diff --git a/.kamal/hooks/pre-deploy b/.kamal/hooks/pre-deploy
--- a/.kamal/hooks/pre-deploy
+++ b/.kamal/hooks/pre-deploy
@@ -1,3 +1,13 @@
 #!/bin/sh
-echo "Cleaning up old honeypot containers..."
+set -eux  # <- exit on error, print each command, treat unset variables as error
+
+echo "Finding existing honeypot containers..."
+docker ps -a --filter "name=my-honeypot" --format "{{.ID}} {{.Names}}" || true
+
+echo "Stopping old honeypot containers..."
+docker ps -a --filter "name=my-honeypot" -q | xargs -r docker stop -t 30
+
+echo "Removing old honeypot containers..."
 docker ps -a --filter "name=my-honeypot" -q | xargs -r docker rm -f
+
+echo "Pre-deploy cleanup finished."
