improve hooks

diff --git a/.kamal/hooks/pre-deploy b/.kamal/hooks/pre-deploy
--- a/.kamal/hooks/pre-deploy
+++ b/.kamal/hooks/pre-deploy
@@ -1,18 +1,19 @@
 #!/bin/sh
 set -eux  # <- exit on error, print each command, treat unset variables as error
 
-env | sort
+kamal app stop
+#env | sort
 
-ssh ubuntu@$KAMAL_HOSTS -p 22222 '
+#ssh ubuntu@$KAMAL_HOSTS -p 22222 '
 
-echo "Finding existing honeypot containers..."
-docker ps -a --filter "name=my-honeypot" --format "{{.ID}} {{.Names}}" || true
+#echo "Finding existing honeypot containers..."
+#docker ps -a --filter "name=my-honeypot" --format "{{.ID}} {{.Names}}" || true
 
-echo "Stopping old honeypot containers..."
-docker ps -a --filter "name=my-honeypot" -q | xargs -r docker stop -t 30
+#echo "Stopping old honeypot containers..."
+#docker ps -a --filter "name=my-honeypot" -q | xargs -r docker stop -t 30
 
-echo "Removing old honeypot containers..."
-docker ps -a --filter "name=my-honeypot" -q | xargs -r docker rm -f
+#echo "Removing old honeypot containers..."
+#docker ps -a --filter "name=my-honeypot" -q | xargs -r docker rm -f
 
-echo "Pre-deploy cleanup finished."
-'
+#echo "Pre-deploy cleanup finished."
+#'
